// <auto-generated />
using System;
using JalcruzFirstClass.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JalcruzFirstClass.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802012802_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<bool>("DidEat")
                        .HasColumnType("boolean")
                        .HasColumnName("did_eat");

                    b.Property<decimal>("ExtraAmount")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("extra_amount");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paid");

                    b.Property<int>("PayrollId")
                        .HasColumnType("integer")
                        .HasColumnName("payroll_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_attendances");

                    b.HasIndex("PayrollId")
                        .HasDatabaseName("ix_attendances_payroll_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_attendances_person_id");

                    b.ToTable("attendances", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Budget")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("budget");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("ExecutionDate")
                        .HasColumnType("date")
                        .HasColumnName("execution_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_campaigns");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_cities_name");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessName")
                        .HasColumnType("text")
                        .HasColumnName("business_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Nit")
                        .HasColumnType("text")
                        .HasColumnName("nit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Commission")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("commission");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EnrollmentDate")
                        .HasColumnType("date")
                        .HasColumnName("enrollment_date");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("ProspectId")
                        .HasColumnType("integer")
                        .HasColumnName("prospect_id");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("text")
                        .HasColumnName("receipt_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_enrollments");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_enrollments_product_id");

                    b.HasIndex("ProspectId")
                        .HasDatabaseName("ix_enrollments_prospect_id");

                    b.ToTable("enrollments", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_entities");

                    b.ToTable("entities", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<int?>("MediaAssetId")
                        .HasColumnType("integer")
                        .HasColumnName("media_asset_id");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<int>("ProspectId")
                        .HasColumnType("integer")
                        .HasColumnName("prospect_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WhatsappMediaUrl")
                        .HasColumnType("text")
                        .HasColumnName("whatsapp_media_url");

                    b.Property<string>("WhatsappMessageId")
                        .HasColumnType("text")
                        .HasColumnName("whatsapp_message_id");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("WhatsappMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_messages_whatsapp_message_id")
                        .HasFilter("whatsapp_message_id IS NOT NULL");

                    b.HasIndex("ProspectId", "CreatedAt")
                        .HasDatabaseName("ix_messages_prospect_id_created_at");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Payroll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WorkAreaId")
                        .HasColumnType("integer")
                        .HasColumnName("work_area_id");

                    b.HasKey("Id")
                        .HasName("pk_payrolls");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_payrolls_code");

                    b.HasIndex("WorkAreaId")
                        .HasDatabaseName("ix_payrolls_work_area_id");

                    b.ToTable("payrolls", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Ci")
                        .HasColumnType("text")
                        .HasColumnName("ci");

                    b.Property<string>("CiComplement")
                        .HasColumnType("text")
                        .HasColumnName("ci_complement");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.HasIndex("Ci")
                        .IsUnique()
                        .HasDatabaseName("ix_people_ci");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_people_city_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_people_email");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("NormalizedNumber")
                        .HasColumnType("text")
                        .HasColumnName("normalized_number");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_phones");

                    b.HasIndex("NormalizedNumber")
                        .HasDatabaseName("ix_phones_normalized_number");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_phones_person_id");

                    b.ToTable("phones", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Prospect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Origin")
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_prospects");

                    b.HasIndex("AssignedToUserId")
                        .HasDatabaseName("ix_prospects_assigned_to_user_id");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_prospects_campaign_id");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_prospects_entity_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_prospects_person_id");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_prospects_zone_id");

                    b.ToTable("prospects", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean")
                        .HasColumnName("is_done");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("ProspectId")
                        .HasColumnType("integer")
                        .HasColumnName("prospect_id");

                    b.Property<DateTime>("RemindAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("remind_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reminders");

                    b.HasIndex("ProspectId")
                        .HasDatabaseName("ix_reminders_prospect_id");

                    b.ToTable("reminders", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Super Admin",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "HR Admin",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CRM Admin",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Specialty")
                        .HasColumnType("text")
                        .HasColumnName("specialty");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_teachers");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.TrialClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AttendanceBool")
                        .HasColumnType("boolean")
                        .HasColumnName("attendance_bool");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ProspectId")
                        .HasColumnType("integer")
                        .HasColumnName("prospect_id");

                    b.Property<int?>("ReprogrammedFromId")
                        .HasColumnType("integer")
                        .HasColumnName("reprogrammed_from_id");

                    b.Property<DateTime>("Schedule")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("schedule");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_trial_classes");

                    b.HasIndex("ProspectId")
                        .HasDatabaseName("ix_trial_classes_prospect_id");

                    b.HasIndex("ReprogrammedFromId")
                        .HasDatabaseName("ix_trial_classes_reprogrammed_from_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_trial_classes_teacher_id");

                    b.ToTable("trial_classes", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.WorkArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("InChargeId")
                        .HasColumnType("integer")
                        .HasColumnName("in_charge_id");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_work_areas");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_work_areas_city_id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_work_areas_company_id");

                    b.HasIndex("InChargeId")
                        .HasDatabaseName("ix_work_areas_in_charge_id");

                    b.ToTable("work_areas", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.WorkerDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<string>("Reliability")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reliability");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_worker_details");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_worker_details_person_id");

                    b.ToTable("worker_details", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_zones");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Attendance", b =>
                {
                    b.HasOne("JalcruzFirstClass.Api.Domain.Payroll", "Payroll")
                        .WithMany("Attendances")
                        .HasForeignKey("PayrollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendances_payrolls_payroll_id");

                    b.HasOne("JalcruzFirstClass.Api.Domain.Person", "Person")
                        .WithMany("Attendances")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendances_people_person_id");

                    b.Navigation("Payroll");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Enrollment", b =>
                {
                    b.HasOne("JalcruzFirstClass.Api.Domain.Product", "Product")
                        .WithMany("Enrollments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_products_product_id");

                    b.HasOne("JalcruzFirstClass.Api.Domain.Prospect", "Prospect")
                        .WithMany("Enrollments")
                        .HasForeignKey("ProspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_prospects_prospect_id");

                    b.Navigation("Product");

                    b.Navigation("Prospect");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Message", b =>
                {
                    b.HasOne("JalcruzFirstClass.Api.Domain.Prospect", "Prospect")
                        .WithMany("Messages")
                        .HasForeignKey("ProspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_prospects_prospect_id");

                    b.Navigation("Prospect");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Payroll", b =>
                {
                    b.HasOne("JalcruzFirstClass.Api.Domain.WorkArea", "WorkArea")
                        .WithMany("Payrolls")
                        .HasForeignKey("WorkAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payrolls_work_areas_work_area_id");

                    b.Navigation("WorkArea");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Person", b =>
                {
                    b.HasOne("JalcruzFirstClass.Api.Domain.City", "City")
                        .WithMany("People")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_people_cities_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Phone", b =>
                {
                    b.HasOne("JalcruzFirstClass.Api.Domain.Person", "Person")
                        .WithMany("Phones")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_phones_people_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Prospect", b =>
                {
                    b.HasOne("JalcruzFirstClass.Api.Domain.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_prospects_users_assigned_to_user_id");

                    b.HasOne("JalcruzFirstClass.Api.Domain.Campaign", "Campaign")
                        .WithMany("Prospects")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_prospects_campaigns_campaign_id");

                    b.HasOne("JalcruzFirstClass.Api.Domain.Entity", "Entity")
                        .WithMany("Prospects")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_prospects_entities_entity_id");

                    b.HasOne("JalcruzFirstClass.Api.Domain.Person", "Person")
                        .WithMany("Prospects")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prospects_people_person_id");

                    b.HasOne("JalcruzFirstClass.Api.Domain.Zone", "Zone")
                        .WithMany("Prospects")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_prospects_zones_zone_id");

                    b.Navigation("AssignedTo");

                    b.Navigation("Campaign");

                    b.Navigation("Entity");

                    b.Navigation("Person");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Reminder", b =>
                {
                    b.HasOne("JalcruzFirstClass.Api.Domain.Prospect", "Prospect")
                        .WithMany("Reminders")
                        .HasForeignKey("ProspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reminders_prospects_prospect_id");

                    b.Navigation("Prospect");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.TrialClass", b =>
                {
                    b.HasOne("JalcruzFirstClass.Api.Domain.Prospect", "Prospect")
                        .WithMany("TrialClasses")
                        .HasForeignKey("ProspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trial_classes_prospects_prospect_id");

                    b.HasOne("JalcruzFirstClass.Api.Domain.TrialClass", "ReprogrammedFrom")
                        .WithMany()
                        .HasForeignKey("ReprogrammedFromId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_trial_classes_trial_classes_reprogrammed_from_id");

                    b.HasOne("JalcruzFirstClass.Api.Domain.Teacher", "Teacher")
                        .WithMany("TrialClasses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_trial_classes_teachers_teacher_id");

                    b.Navigation("Prospect");

                    b.Navigation("ReprogrammedFrom");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.UserRole", b =>
                {
                    b.HasOne("JalcruzFirstClass.Api.Domain.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("JalcruzFirstClass.Api.Domain.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.WorkArea", b =>
                {
                    b.HasOne("JalcruzFirstClass.Api.Domain.City", "City")
                        .WithMany("WorkAreas")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_areas_cities_city_id");

                    b.HasOne("JalcruzFirstClass.Api.Domain.Company", "Company")
                        .WithMany("WorkAreas")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_areas_companies_company_id");

                    b.HasOne("JalcruzFirstClass.Api.Domain.Person", "InCharge")
                        .WithMany()
                        .HasForeignKey("InChargeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_work_areas_people_in_charge_id");

                    b.Navigation("City");

                    b.Navigation("Company");

                    b.Navigation("InCharge");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.WorkerDetail", b =>
                {
                    b.HasOne("JalcruzFirstClass.Api.Domain.Person", "Person")
                        .WithOne("WorkerDetail")
                        .HasForeignKey("JalcruzFirstClass.Api.Domain.WorkerDetail", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_worker_details_people_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Campaign", b =>
                {
                    b.Navigation("Prospects");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.City", b =>
                {
                    b.Navigation("People");

                    b.Navigation("WorkAreas");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Company", b =>
                {
                    b.Navigation("WorkAreas");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Entity", b =>
                {
                    b.Navigation("Prospects");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Payroll", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Person", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Phones");

                    b.Navigation("Prospects");

                    b.Navigation("WorkerDetail");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Product", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Prospect", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Messages");

                    b.Navigation("Reminders");

                    b.Navigation("TrialClasses");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Teacher", b =>
                {
                    b.Navigation("TrialClasses");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.WorkArea", b =>
                {
                    b.Navigation("Payrolls");
                });

            modelBuilder.Entity("JalcruzFirstClass.Api.Domain.Zone", b =>
                {
                    b.Navigation("Prospects");
                });
#pragma warning restore 612, 618
        }
    }
}
